### ISSUE TITLE
设置Fragment与导航Fragment混乱问题

### ISSUE THREAD

**Issue by LZKDreamer** [JsonChao/Awesome-WanAndroid#100]
在侧边栏选择设置，然后选择WanAndroid,底部导航栏再选择导航，导航里面显示的是设置里面的内容.

**Comment by JsonChao** [comment]
Thank your issue，我这边没有出现过这种问题，能否再描述清楚一点吗？

**Comment by LZKDreamer** [comment]
现在没有这个问题了，可能是之前我手机卡了，不好意思
