### ISSUE TITLE
A simple question

### ISSUE THREAD

**Issue by toolperson** [JsonChao/Awesome-WanAndroid#102]
![2](https://user-images.githubusercontent.com/52614822/65208416-9b475080-dac7-11e9-9fe6-e46c2c8f7aa2.png)
I haven't seen this structure ever before . Does this mean that the dependencies have been downloaded locally since I clone the project from the github?
Looking forward to your reply ! Thanks !

**Comment by toolperson** [comment]
![image](https://user-images.githubusercontent.com/52614822/65209049-70f69280-dac9-11e9-965b-7734247a1d7a.png)
I saw the file here . But I don't know how to achieve this . Maybe I should learn gradle first ？

**Comment by JsonChao** [comment]
Thank your issue, yes, you must to learn gradle first~
