### ISSUE TITLE
为什么该项目不支持API19的？

### ISSUE THREAD

**Issue by Avail0723** [JsonChao/Awesome-WanAndroid#12]
为什么不能设置minSdkVersion = 19？

**Comment by JsonChao** [comment]
Thanks your issue, 可以设置支持Andorid 4.4的版本，但是5.0以下是看不到MD的效果哦~

**Comment by Avail0723** [comment]
我设置后编译会报错：Can't process attribute android:fillColor="@android:color/white": references to other resources are not supported by build-time PNG generation.

**Comment by JsonChao** [comment]
项目中使用了svg(VectorDrawable)，Android4.4需要使用支持库，在app的build.gradle中的defaultConfig里面加上vectorDrawables.useSupportLibrary = true即可

**Comment by JsonChao** [comment]
不是大佬，一起学习进步嘛~

**Comment by Avail0723** [comment]
这个框架我感觉挺厉害的，我都写不出来，需要费不少劲去研究，大佬就是大佬哈

**Comment by JsonChao** [comment]
一起学习~

**Comment by Avail0723** [comment]
好的
