### ISSUE TITLE
NavigationFragment

### ISSUE THREAD

**Issue by xiyangyang8110** [JsonChao/Awesome-WanAndroid#17]
103行，setTextColor(0xFF36BC9B, 0xFF757575)色值直接硬编进去不好吧
`@Override
            public ITabView.TabTitle getTitle(int i) {
                return new TabView.TabTitle.Builder()
                        .setContent(navigationListData.get(i).getName())
                        .setTextColor(0xFF36BC9B, 0xFF757575)
                        .build();
            }`

**Comment by JsonChao** [comment]
Thank your issue, 现已修正~
