### ISSUE TITLE
建议Glide的参数不要直接传ApplicationContext

### ISSUE THREAD

**Issue by TangHuaiZhe** [JsonChao/Awesome-WanAndroid#18]
当 Glide.with() 中传入的 Activity 或 Fragment 实例销毁时，Glide 会自动取消加载并回收资源。

可参考：
> https://muyangmin.github.io/glide-docs-cn/doc/getting-started.html

**Comment by JsonChao** [comment]
Thank your issue，项目只有2个地方用到了Glide，但是都没有传入ApplicationContext

**Comment by TangHuaiZhe** [comment]
@JsonChao  抱歉 我看到的地方是传了ApplicationCtx

`在GlideLoaderManager.java中:
Glide.with(AppContext.getContext()).load(url).apply(head_options).into(imageView);
`

```
而在AppContext.java中:
    public static Context getContext() {
        return mContext;
    }
  ……
   mInstance = new AppContext(context.getApplicationContext());
 ……
```
