### ISSUE TITLE
关于依赖注入的使用

### ISSUE THREAD

**Issue by iwenchao** [JsonChao/Awesome-WanAndroid#19]
initInject（）在每个activity中进行注入，方式不是很友好；
我这有个不太成熟的建议：通过反射的方式，统一在基类中注入

**Comment by JsonChao** [comment]
Thank your issue, 首先，反射比较耗性能，其次，在基类中注入会显得不够灵活，之所以使用抽象方法的方式让对应的Activity或Fragment实现，就是为了能够具备灵活的依赖注入~
