### ISSUE TITLE
android5.1.1闪退停止运行

### ISSUE THREAD

**Issue by prince70** [JsonChao/Awesome-WanAndroid#21]
首页的item点进去，返回就报错
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.ViewGroup.getScrollX()' on a null object reference

**Comment by JsonChao** [comment]
Thank your issue，ShareElement Animation在部分三星机型和Android 5.0/5.1上会出现崩溃的情况，现在已在代码中进行了过滤，最新的apk 二维码可供下载~
