### ISSUE TITLE
崩溃了～试玩了apk5分钟崩溃了5次，应该都是在这个地方。

### ISSUE THREAD

**Issue by yungelee** [JsonChao/Awesome-WanAndroid#22]
其实这两种方式都是可以的，就看服务器对客户端的要求，你可以先安装试试看还会出现崩溃不～

**Comment by yungelee** [comment]
其实我是想来学习一下注册登录的流程,你的项目里面这一块实用性高吗；

**Comment by JsonChao** [comment]
Thank your issue，ShareElement Animation在部分三星机型和Android 5.0/5.1上会出现崩溃的情况，现在已在代码中进行了过滤，最新的apk 二维码可供下载~

**Comment by JsonChao** [comment]
流程方面基本是没问题的，但是商用的话必须得结合你们项目的实际情况，对账号、密码的限制等等方面一般是由自己公司产品来决策的

**Comment by yungelee** [comment]
好的额，我有时间看下你的这块代码；你们商用接口对token有需求的时候是同时要带上userid吗？我理解是这样的，但是有的朋友说不需要userid，只通过token找用户。。。不懂这块，还请给点经验。然后，我今天试玩的机器是7.0荣耀8的，应该好像没有点击share分享这个功能，好像是都在主Tab下滑动的时候蹦的。

**Comment by JsonChao** [comment]
其实这两种方式都是可以的，就看服务器对客户端的要求，你可以先安装试试看还会出现崩溃不～
