### ISSUE TITLE
玩了10几分钟，感觉细节处理的不是特别好，比如下拉刷新，加载更多的动画，效果是酷炫但是过渡效果不是很流畅，有时候突然很大有时候突然消失！

### ISSUE THREAD

**Issue by zhengqunwei** [JsonChao/Awesome-WanAndroid#23]

**Comment by JsonChao** [comment]
Thank your issue, 流畅度可能跟机型的版本、配置有关，至于“有时候突然很大有时候突然消失”这个描述无法定位问题。。

**Comment by zhengqunwei** [comment]
下拉刷新头部动画

**Comment by JsonChao** [comment]
下拉刷新的动画流畅度是跟SmartRefreshLayout内部的机制有关，当然，app里面也有一些内存占用的问题会使动画的流畅度受损，目前，app已经对内存占用方面做了比较大的优化，可pull代码跑跑试试~
