### ISSUE TITLE
点击项目向右快速滑动 日志大批量 gc 卡顿

### ISSUE THREAD

**Issue by tianshaokai** [JsonChao/Awesome-WanAndroid#24]
![image](https://user-images.githubusercontent.com/6706496/39050733-0339c708-44d9-11e8-8d71-359198153a27.png)

**Comment by tianshaokai** [comment]
04-21 11:13:56.942 1842-1872/? E/ActivityManager: ANR in json.chao.com.wanandroid (json.chao.com.wanandroid/.ui.main.activity.MainActivity)
                                                  PID: 9986
                                                  Reason: Input dispatching timed out (json.chao.com.wanandroid/json.chao.com.wanandroid.ui.main.activity.MainActivity, Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 21.  Wait queue head age: 5618.9ms.)
                                                  Load: 11.74 / 10.02 / 5.41
                                                  CPU usage from 381677ms to 0ms ago:
                                                    18% 1842/system_server: 12% user + 5.6% kernel / faults: 33105 minor 112 major
                                                    4.1% 5391/perfd: 2.4% user + 1.6% kernel / faults: 10047 minor 5 major
                                                    3% 276/surfaceflinger: 1.5% user + 1.5% kernel / faults: 735 minor 7 major
                                                    2.9% 3516/android.process.media: 1.6% user + 1.2% kernel / faults: 18137 minor 51 major
                                                    2.6% 3469/adbd: 0.3% user + 2.2% kernel / faults: 7829 minor
                                                    1% 3550/com.android.systemui: 0.7% user + 0.3% kernel / faults: 9955 minor 28 major
                                                    1% 103/kswapd0: 0% user + 1% kernel
                                                    0.9% 3510/sdcard: 0% user + 0.8% kernel / faults: 248 minor
                                                    0.9% 222/logd: 0.5% user + 0.4% kernel / faults: 707 minor
                                                    0.7% 208/ueventd: 0.2% user + 0.4% kernel / faults: 44 minor
                                                    0.7% 193/mmcqd/0: 0% user + 0.7% kernel
                                                    0.6% 4445/com.miui.home: 0.5% user + 0.1% kernel / faults: 15598 minor 48 major
                                                    0.6% 296/rild: 0.4% user + 0.1% kernel / faults: 2116 minor 2 major
                                                    0.6% 331/displayfeature: 0.4% user + 0.1% kernel / faults: 79 minor
                                                    0.5% 5405/mpdecision: 0% user + 0.5% kernel / faults: 647 minor
                                                    0.4% 4409/com.android.phone: 0.2% user + 0.1% kernel / faults: 7321 minor 18 major
                                                    0.4% 604/mdss_fb0: 0% user + 0.4% kernel
                                                    0.3% 4006/com.miui.powerkeeper:service: 0.2% user + 0.1% kernel / faults: 7316 minor 24 major
                                                    0.3% 3952/com.miui.securitycenter.remote: 0.2% user + 0.1% kernel / faults: 9258 minor 40 major
                                                    0.2% 3532/logcat: 0.1% user + 0.1% kernel / faults: 67 minor
                                                    0.2% 275/servicemanager: 0% user + 0.1% kernel / faults: 95 minor
                                                    0.2% 3/ksoftirqd/0: 0% user + 0.2% kernel
                                                    0.2% 190/kworker/u:4: 0% user + 0.2% kernel
                                                    0.2% 7/kworker/u:0H: 0% user + 0.2% kernel
                                                    0.2% 556/sensors.qcom: 0% user + 0.1% kernel / faults: 258 minor
                                                    0.2% 4314/com.xiaomi.metoknlp: 0.1% user + 0% kernel / faults: 17069 minor 36 major
                                                    0.2% 192/kworker/0:3: 0% user + 0.2% kernel
                                                    0.1% 172/kworker/u:3: 0% user + 0.1% kernel
                                                    0.1% 411/irq/33-cpubw_hw: 0% user + 0.1% kernel
                                                    0.1% 5428/ksoftirqd/3: 0% user + 0.1% kernel
                                                    0.1% 6619/com.tencent.mm:push: 0.1% user + 0% kernel / faults: 7256 minor 5 major
                                                    0.1% 445/qmuxd: 0% user + 0% kernel / faults: 2093 minor
                                                    0.1% 442/mm-pp-daemon: 0% user + 0% kernel / faults: 136 minor
                                                    0.1% 5392/kworker/u:5: 0% user + 0.1% kernel
                                                    0.1% 214/flush-179:0: 0% user + 0.1% kernel
                                                    0.1% 4384/com.miui.daemon: 0% user + 0% kernel / faults: 3882 minor 16 major
                                                    0.1% 293/netd: 0% user + 0.1% kernel / faults: 2823 minor
                                                    0.1% 5540/com.miui.systemAdSolution: 0% user + 0% kernel / faults: 6740 minor 5 major
                                                    0.1% 247/kworker/0:4: 0% user + 0.1% kernel
                                                    0.1% 3658/com.xiaomi.account: 0% user + 0% kernel / faults: 3434 minor 3 major
                                                    0.1% 3687/com.miui.whetstone: 0% user + 0% kernel / faults: 1886 minor 10 major
                                                    0.1% 5430/kworker/3:0H: 0% user + 0.1% kernel
                                                    0.1% 6/kworker/u:0: 0% user + 0.1% kernel
                                                    0% 5432/kworker/3:0: 0% user + 0% kernel
                                                    0% 4273/com.sohu.inputmethod.sogou.xiaomi: 0% user + 0% kernel / faults: 5583 minor 75 major
                                                    0% 27/kworker/0:1H: 0% user + 0% kernel
                                                    0% 311/zygote: 0% user + 0% kernel / faults: 28722 minor
                                                    0% 54/system: 0% user + 0% kernel
                                                    0% 163/cfinteractive: 0% user + 0% kernel
                                                    0% 4401/com.xiaomi.finddevice: 0% user + 0% kernel / faults: 1771 minor 2 major
                                                    0% 6393/com.miui.cloudservice: 0% user + 0% kernel / faults: 6224 minor 3 major
                                                    0% 1//init: 0% user + 0% kernel / faults: 108 minor 4 major
                                                    0% 336/thermal-engine: 0% user + 0% kernel / faults: 112 minor
                                                    0% 3564/RX_Thread: 0% user + 0% kernel
                                                    0% 5736/com.tencent.mm: 0% user + 0% kernel / faults: 2094 minor 20 major
                                                    0% 3563/TX_Thread: 0% user + 0% kernel
                                                    0% 216/jbd2/mmcbl
04-21 11:13:56.945 9986-9995/json.chao.com.wanandroid I/art: Waiting for a blocking GC Alloc
04-21 11:13:56.946 9986-10031/json.chao.com.wanandroid I/art: Waiting for a blocking GC Alloc
04-21 11:13:56.948 1842-1872/? D/PerfShielderService: json.chao.com.wanandroid|json.chao.com.wanandroid/.ui.main.activity.MainActivity|5000|1524280436947|5000|7
04-21 11:13:56.949 4384-5792/? D/MiuiPerfServiceClient: interceptAndQueuing:9986|json.chao.com.wanandroid|5000|5000|unknown|null

**Comment by JsonChao** [comment]
Thank your issue, 内存占用过多的问题大致是因为图片占用内存过大和ViewPager复用回收机制导致的，目前已经全局对Glide配置了内存优化机制，并同时处理了ViewPager复用回收机制导致的问题，可pull最新的代码查看~

**Comment by tianshaokai** [comment]
@JsonChao  对 anr 文件你是如何分析的呢？有点不懂

**Comment by tianshaokai** [comment]
这次直接内存溢出了

**Comment by tianshaokai** [comment]
点击项目滑动 内存消耗很大，会造成内存溢出

**Comment by JsonChao** [comment]
是的，用Andorid Profile查看了好几次，内存占用比较高，虽然我的手机没有内存溢出（手机内存大），但是也达到了300多MB的占用。现在对图片解析格式、Glide的内存、磁盘、BitmapPool做了一定的配置、以及使用FragmentStatePagerAdapter替代FragmentPagerAdapter，避免缓存大量的界面，现在我的手机只占用170MB了，应该在你的机型上不会造成OOM了，pull下最新的代码试试吧~

**Comment by tianshaokai** [comment]
没看懂哪里比较消耗内存

**Comment by JsonChao** [comment]
上面的log没发现报内存方面的错误，是有关ANR方面的问题，估计是哪块代码执行了耗时操作~
