### ISSUE TITLE
解析框架封装的不合理呀

### ISSUE THREAD

**Issue by nianzixin** [JsonChao/Awesome-WanAndroid#26]
feedArticleListResponse.getErrorCode() == BaseResponse.SUCCESS

比如每个接口都要这样的判断么，实际情况这个接口返回异常字段有好多种呢？不能每个接口都要这样判断吧，能不能封装个基类出来？（由于对RxJava不熟悉，只能请教您了）

**Comment by JsonChao** [comment]
Thank your issue，的确，可以使用compose的方式将类似这样的判断操作封装起来，会使程序的可维护行和扩展性更强，后面会将其加入的~

**Comment by nianzixin** [comment]
您好，能尽快分装解决嘛？想把您的框架用在项目上。

**Comment by JsonChao** [comment]
估计这几天会将改进版本上传的

**Comment by JsonChao** [comment]
改进版本已上传~
