### ISSUE TITLE
No cached version of com.github.bumptech.glide:compiler:4.0.0 available for offline mode.

### ISSUE THREAD

**Issue by Sumu2017** [JsonChao/Awesome-WanAndroid#28]
设置里面的offline work未勾选，也尝试翻墙，换版本都不行，编译可以通过，一旦运行就会报这个错误，Gradle没升级，as版本 3.1

**Comment by JsonChao** [comment]
Thank your issue，可以将Glide降级，也可以手动下载4.0的版本放到Glide对应的缓存目录中~

**Comment by JsonChao** [comment]
可能是你的Gradle版本比较老造成的

**Comment by Sumu2017** [comment]
Gradle没动还是3.0.1哎，刚刚升级了，3.1.0,又出现Could not get unknown property 'packageForR' for task ':app:processDebugResources' of type com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask.这个问题，好像是butterknife兼容问题，唉，不跑了，就看看代码吧 ，搞了两天都没跑起来

**Comment by Sumu2017** [comment]
发现点击注册后，不能取消注册界面。。。点返回键也没用

**Comment by JsonChao** [comment]
Could not get unknown property 'packageForR' for task ':app:processDebugResources' of type com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask.----这个问题是由as 3.1.0跟ButterKnife最新的插件间不协调所产生的，目前，只能等ButterKnife最新的插件版本下来。
----------
在某些手机上出现PopWindow无法取消的原因是PopWinodw没有一个默认的背景drawable，从PopWindow的源码分析可知，只有当PopWindow有背景drawable时，才会处理返回退出和点击外部退出的逻辑~

**Comment by Sumu2017** [comment]
好的好的  感谢感谢
