### ISSUE TITLE
发现了几个问题

### ISSUE THREAD

**Issue by tianshaokai** [JsonChao/Awesome-WanAndroid#32]
日志里有这个错误
1. Called reconfigure on a bitmap that is in use! This may cause graphical corruption!

2. 
![29b50559-d2d5-4503-888c-7459a7e44d77](https://user-images.githubusercontent.com/6706496/39668644-bdcf046a-5105-11e8-9e53-e5954c4ce51a.png)

3. square leakcanary   提示 projectlistfragment 内存泄露

**Comment by JsonChao** [comment]
Thank your issue，
第一个问题，这是Glide内部对bitmap的操作产生的，其实并不会产生所谓的corruption（崩溃），详情见https://github.com/bumptech/glide/issues/743。
第二个问题InvocationTargetException是BaseRecyclerViewAdapter自身在BaseQuickAdapter使用了不太规范的反射导致的，也是可以忽略的，下面报的控件找不到的错误是ButterKnife没有生成控件绑定辅助类，重新build即可。
第三个问题报的错误是static ActivityThread.sCurrentActivityThread的相关问题，在leakcanary的issue处理中可以得知可以忽略此类提示~
