### ISSUE TITLE
关于列表加载更多失败的情况处理

### ISSUE THREAD

**Issue by magic0908** [JsonChao/Awesome-WanAndroid#33]
首先感谢楼主提供这样的学习demo，不过我觉得有些地方可以优化一下。
比如列表加载更多失败，你目前的处理都是统一显示失败的view，这样之前的内容就被挡住了，体验不是那么好。我觉得可以用BaseQuickAdapter的加载更多监听，正在加载更多失败的时候，列表底部显示加载失败，点击可以重新加载，前面的内容不至于被覆盖。

**Comment by JsonChao** [comment]
Thank your issue, 列表加载更多失败时已取消显示ErrorView，目前只在第一次加载失败时做显示ErrorView的处理，对于刷新和加载更多监听，已全局采用SmartRefreshLayout的监听处理了~
