### ISSUE TITLE
直接github上down下来的，然后导入AndroidStudio后依赖出错

### ISSUE THREAD

**Issue by sh1018727638** [JsonChao/Awesome-WanAndroid#38]
google后发现有相当一部分的类似问题，尝试了很多方法，但未能解决，想请问一下Chao哥有过类似的问题吗，困扰了很久，敬请解答。
以下为报错信息：
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.github.githubwing:ByeBurger:1.2.3.
Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.github.githubwing:ByeBurger:1.2.3.
Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.github.githubwing:ByeBurger:1.2.3.
Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not download byte-buddy.jar (net.bytebuddy:byte-buddy:1.7.4)
Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve com.github.githubwing:ByeBurger:1.2.3.
Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve com.github.githubwing:ByeBurger:1.2.3.
Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not download byte-buddy.jar (net.bytebuddy:byte-buddy:1.7.4)

**Comment by JsonChao** [comment]
Thank your issue，这种问题导致的原因有很多，以前遇到过，我是换了gradle-wrapper.properties的版本，然后clean，rebuild后就可以了或者检查下依赖和被依赖module中的 buildTypes {}，二者包含子项（ release {} debug{}…）要相同。 你可以看看这个
https://stackoverflow.com/questions/46949622/android-studio-3-0-unable-to-resolve-dependency-for-appdexoptions-compileclas
