### ISSUE TITLE
把 classpath 'com.android.tools.build:gradle:2.3.3' 改成 classpath 'com.android.tools.build:gradle:3.0.1' 时项目会构建失败。

### ISSUE THREAD

**Issue by dzzchao** [JsonChao/Awesome-WanAndroid#4]
把 classpath 'com.android.tools.build:gradle:2.3.3' 改成 classpath 'com.android.tools.build:gradle:3.0.1' 时项目会构建失败。

**Comment by JsonChao** [comment]
感谢您提的issue,项目目前没有进行gradle3.0的升级配置，后期会跟进此升级

**Comment by magical-xu** [comment]
把 apt 和 butterKnife 相关的插件 干掉 ， 把 apt 换成 annotationProcessor   @dzzchao
