### ISSUE TITLE
app闪退

### ISSUE THREAD

**Issue by gaolhjy** [JsonChao/Awesome-WanAndroid#42]
1.退出app时,出现报空指针的闪退. 
 java.lang.NullPointerException: Attempt to invoke virtual method 'void com.squareup.leakcanary.RefWatcher.watch(java.lang.Object)' on a null object reference
                      at json.chao.com.wanandroid.base.fragment.AbstractSimpleFragment.onDestroy(AbstractSimpleFragment.java:54)

2.项目/富文本 或其他几个tablayout都是空指针的闪退.

**Comment by JsonChao** [comment]
Thank your issue, 这个是在单元测试的时候注释了WanAndroidApp里面的部分初始化代码导致的，现已修正~
