### ISSUE TITLE
代码中的一些疑惑

### ISSUE THREAD

**Issue by wjploop** [JsonChao/Awesome-WanAndroid#45]
我是跟着你的这个项目学习，期间遇到了几个问题。
1. 
  @Override
    public void showLoginSuccess() {
        CommonUtils.showSnackMessage(this, getString(R.string.login_success));
        onBackPressedSupport();
    }
Snackbar调用显示的方法之后，立即关闭该activity，按理说，这个Snackbar应该不会被显示，（我的正是存在这个问题，snackbar没有显示）。
查看工具类中的显示snackar方法，view是附带到decorView....
Snackbar snackbar = Snackbar.make(activity.getWindow().getDecorView(), msg, Snackbar.LENGTH_SHORT);
可是，即使如此，我还是的代码还是有问题。
简单说，若不关闭activity，消息提示没问题，否则，没有消息提示。

我想应该是我遗漏了什么，望解答。

**Comment by JsonChao** [comment]
Thank your issue，Snackbar的视图是跟Activity的根视图DecoView关联的，因此，Activity被销毁时，Snackbar也会随之消失。此种情况，已改为使用吐司。
