### ISSUE TITLE
有一个内存泄漏的问题

### ISSUE THREAD

**Issue by liuhang1234** [JsonChao/Awesome-WanAndroid#47]
![device-2018-08-02-154448](https://user-images.githubusercontent.com/22323970/43569837-4841cc36-966b-11e8-924d-36f799d9bdd5.png)

**Comment by JsonChao** [comment]
Thank your issue, 这个是Android系统自身的bug，并不会有实质性的内存泄漏，网上的现有的一些解决方案都不是很稳定，因此，暂时没有对此处理，之后想到好的解决方式会尽快处理的~
