### ISSUE TITLE
android studio 2.1.2版本怎么编译运行这个项目呢？

### ISSUE THREAD

**Issue by wuyanhong3** [JsonChao/Awesome-WanAndroid#48]
android studio 2.1.2版本怎么编译运行这个项目呢，build.gradle中的配置都改了，还是运行不了，

**Comment by JsonChao** [comment]
Thank your issue，项目目前采用的是Android Studio 3.0以上的版本，跟3.0以下的配置差别比较大，建议升级到3.0~
