### ISSUE TITLE
No adapter attached; skipping layout

### ISSUE THREAD

**Issue by wjploop** [JsonChao/Awesome-WanAndroid#49]
如题，尽管数据正常显示，但想知道具体是哪出现了问题。
猜测是第一layout出现了问题。

**Comment by JsonChao** [comment]
Thank your issue，你的问题描述很不准确。。，请尽量描述准确一点~

**Comment by JsonChao** [comment]
这是setAdapter方法内部引起的，只要没在Activity的onCreate()或Fragment的onCreateView()中初始化setAdapter，就会抛出这个异常，现已解决，最新二维码可供下载~
