### ISSUE TITLE
我在build的时候报了这个错，但是我的版本是在线的 请帮我看一下~ 谢谢

### ISSUE THREAD

**Issue by lovebluedan** [JsonChao/Awesome-WanAndroid#5]
Error:Execution failed for task ':app:compileRetrolambdaDebug'.
> Could not resolve all files for configuration ':app:retrolambdaConfig'.
   > Could not resolve net.orfjackal.retrolambda:retrolambda:2.1.0.
     Required by:
         project :app
      > No cached version of net.orfjackal.retrolambda:retrolambda:2.1.0 available for offline mode.
      > No cached version of net.orfjackal.retrolambda:retrolambda:2.1.0 available for offline mode.
      > No cached version of net.orfjackal.retrolambda:retrolambda:2.1.0 available for offline mode.
      > No cached version of net.orfjackal.retrolambda:retrolambda:2.1.0 available for offline mode.
      > No cached version of net.orfjackal.retrolambda:retrolambda:2.1.0 available for offline mode.

**Comment by JsonChao** [comment]
buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
//            signingConfig signingConfigs.release
        }
        debug {
//            signingConfig signingConfigs.release
        }
    }
感谢您提的issue，在app下的build.gradle中注释掉这两行试试能够解决。

**Comment by lovebluedan** [comment]
`apply plugin: 'com.android.application'
apply plugin: 'com.jakewharton.butterknife'
apply plugin: 'org.greenrobot.greendao'
apply plugin: 'com.neenbedankt.android-apt'// 注释处理
apply plugin: 'me.tatarka.retrolambda'


android {

    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion
//    signingConfigs {
//        release {
//            storeFile file(RELEASE_STORE_FILE)
//            storePassword RELEASE_STORE_PASSWORD
//            keyAlias RELEASE_KEY_ALIAS
//            keyPassword RELEASE_KEY_PASSWORD
//        }
//    }
    defaultConfig {
        applicationId "json.chao.com.wanandroid"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 2
        versionName "1.0.1"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        renderscriptTargetApi 21
        renderscriptSupportModeEnabled true    // Enable RS support
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
//            signingConfig signingConfigs.release
        }
        debug {
//            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    packagingOptions {
        exclude 'META-INF/services/javax.annotation.processing.Processor'
    }

    dexOptions {
        jumboMode true
        javaMaxHeapSize "4g"
    }
}

greendao {
    schemaVersion 1
    targetGenDir 'src/main/java'
    daoPackage 'json.chao.com.wanandroid.core.dao'
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })

    //base
    compile "com.android.support:appcompat-v7:$rootProject.supportLibraryVersion"
    compile "com.android.support:cardview-v7:$rootProject.supportLibraryVersion"
    compile "com.android.support:support-v4:$rootProject.supportLibraryVersion"
    compile "com.android.support:design:$rootProject.supportLibraryVersion"
    compile "com.android.support.constraint:constraint-layout:$rootProject.constraintVersion"

    //ui
    compile "com.scwang.smartrefresh:SmartRefreshLayout:$rootProject.smartrefreshVersion"
    compile "com.scwang.smartrefresh:SmartRefreshHeader:$rootProject.smartrefreshVersion"
    compile "com.youth.banner:banner:$rootProject.bannerVersion"
    compile "com.flyco.tablayout:FlycoTabLayout_Lib:$rootProject.tablayoutVersion"
    compile "q.rorbin:VerticalTabLayout:$rootProject.verticalTabLayoutVersion"
    compile "com.hyman:flowlayout-lib:$rootProject.flowlayoutVersion"
    compile 'com.just.agentweb:agentweb:3.1.0'

    //net
    compile "com.google.code.gson:gson:$rootProject.gsonVersion"
    compile "com.squareup.okhttp3:okhttp:$rootProject.okhttpVersion"
    compile "com.squareup.okhttp3:logging-interceptor:$rootProject.okhttpVersion"
    compile "com.squareup.retrofit2:retrofit:$rootProject.retrofitVersion"
    compile "com.squareup.retrofit2:converter-gson:$rootProject.retrofitVersion"
    compile "com.squareup.retrofit2:adapter-rxjava2:$rootProject.retrofitVersion"
    compile "com.github.bumptech.glide:glide:$rootProject.glideVersion"
    annotationProcessor "com.github.bumptech.glide:compiler:$rootProject.glideVersion"

    //dao
    compile "org.greenrobot:greendao:$rootProject.greendaoVersion"

    //rx
    compile "io.reactivex.rxjava2:rxjava:$rootProject.rxjavaVersion"
    compile "io.reactivex.rxjava2:rxandroid:$rootProject.rxandroidVersion"
    compile "com.jakewharton.rxbinding2:rxbinding:$rootProject.rxbindingVersion"
    compile "com.tbruyelle.rxpermissions2:rxpermissions:$rootProject.rxpermissionsVersion"

    //di
    compile "com.google.dagger:dagger:$rootProject.daggerVersion"
    apt "com.google.dagger:dagger-compiler:$rootProject.daggerVersion"
    compile "org.glassfish:javax.annotation:$rootProject.javaxVersion"
    compile "com.jakewharton:butterknife:$rootProject.butterknifeVersion"
    apt "com.jakewharton:butterknife-compiler:$rootProject.butterknifeVersion"

    //other
    compile "com.airbnb.android:lottie:$rootProject.lottieVersion"
    compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.34'
    compile "me.yokeyword:fragmentation:$rootProject.fragmentationVersion"
    compile "me.yokeyword:fragmentation-swipeback:$rootProject.fragmentationVersion"
    compile 'com.tencent.bugly:crashreport_upgrade:latest.release'
    compile "com.orhanobut:logger:$rootProject.loggerVersion"
    compile "com.github.githubwing:ByeBurger:$rootProject.ByeBurgerVersion"

    //canary
    debugCompile "com.squareup.leakcanary:leakcanary-android:$rootProject.leakcanaryVersion"
    releaseCompile "com.squareup.leakcanary:leakcanary-android-no-op:$rootProject.leakcanaryVersion"
    testCompile "com.squareup.leakcanary:leakcanary-android-no-op:$rootProject.leakcanaryVersion"

    //unit test
    testCompile "junit:junit:$rootProject.junitVersion"
}

//解决支持库版本不兼容问题
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            if (!requested.name.startsWith("multidex")) {
                details.useVersion '25.3.0'
            }
        }
    }
}
repositories {
    mavenCentral()
}
`
但是还是报这个问题

**Comment by lovebluedan** [comment]
上面是build.gradle的所有语句

**Comment by JsonChao** [comment]
试试这个https://my.oschina.net/zhangdengjiexuyu/blog/701311

**Comment by lovebluedan** [comment]
好的 已经处理好了 给个大大的赞给你 谢谢哈

**Comment by JsonChao** [comment]
不用谢，一起加油～
