### ISSUE TITLE
关于懒加载的疑问

### ISSUE THREAD

**Issue by wjploop** [JsonChao/Awesome-WanAndroid#51]
不好意思，上个疑问没有描述清楚。。。
承接上一个疑问：
下面三段代码
//你的代码
    @Override
    public void onLazyInitView(@Nullable Bundle savedInstanceState) {
        super.onLazyInitView(savedInstanceState);
        initEventAndData();
    }

//yokey的
    /**
     * Lazy initial，Called when fragment is first called.
     * <p>
     * 同级下的 懒加载 ＋ ViewPager下的懒加载  的结合回调方法
     */
    @Override
    public void onLazyInitView(@Nullable Bundle savedInstanceState) {
        mDelegate.onLazyInitView(savedInstanceState);
    }

//fragment
    // Hint provided by the app that this fragment is currently visible to the user.
    boolean mUserVisibleHint = true;

以我的猜测，懒加载是在根据mUserVisibleHint和一个记录Fragment是否创建的标志变量来确定。
onLazyInitView()不会在createView之后调用，而是等到Fragment可见。

问题来了，onLazyInitView()之前，onCreateView()方法不应该已经调用了吗？

或是说，根据onLazyInitView方法名的含义，这里懒加载指的不是视图所需的数据，而是整个fragment，所以RecyclerView.setAdapter()调用出现了在onCreated生命周期之外，
那么，这个onLazyInitView是在何时调用的？

**Comment by JsonChao** [comment]
一般情况下来说，onLazyInitView()比onCreateView()慢。关于Fragmentation库中懒加载的含义：
用户第一次可见这个Fragment时会触发这个方法， 比如ViewPager加载了2个Fragment， 第二个Fragment会一进来就走onCreateView， 不走onLazyInitView， 只有当你第一次切换到第二个Fragment时才会触发onLazyInitView。

**Comment by JsonChao** [comment]
Thank your issue， 一般情况下来说，onLazyInitView()比onCreateView()慢。关于Fragmentation库中懒加载的含义：
用户第一次可见这个Fragment时会触发这个方法， 比如ViewPager加载了2个Fragment， 第二个Fragment会一进来就走onCreateView， 不走onLazyInitView， 只有当你第一次切换到第二个Fragment时才会触发onLazyInitView。
