### ISSUE TITLE
关于MVP问题

### ISSUE THREAD

**Issue by maoxiandemeng** [JsonChao/Awesome-WanAndroid#6]
你说这是MVP框架，但是我没看到M层相关，你的请求也是在P层处理，不是应该在M层处理吗？想请教下

**Comment by JsonChao** [comment]
感谢您的Issue，core包即model层代码，对于mvp+rxjava的详细解释请见：https://github.com/googlesamples/android-architecture/tree/todo-mvp-rxjava/

**Comment by maoxiandemeng** [comment]
我记得官方demo也是在M层进行网络请求得到数据，我看到你是在P层做的网络请求操作。你的core包是封装网络的我知道，不知道你有没有懂我的意思  捂脸

**Comment by JsonChao** [comment]
我明白您的意思，core包其实就是model包，拿db来说，DbHelper就相当于mode层接口，GreenDaoHelper相当于model层接口对应的实现类，这样理解是不是更对路一点
