### ISSUE TITLE
考虑加个公众号模块么~

### ISSUE THREAD

**Issue by hongyangAndroid** [JsonChao/Awesome-WanAndroid#69]
[公众号Tab](http://www.wanandroid.com/wxarticle/list/408/1) 

[API](http://www.wanandroid.com/blog/show/2)

 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by JsonChao** [comment]
最近几个月排学习计划有点紧凑，我会尽快挤出时间新增公众号模块的( •̀∀•́ )～


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by JsonChao** [comment]
@hongyangAndroid 鸿神，最新版本已上线公众号模块QAQ~

**Comment by hongyangAndroid** [comment]
感谢支持！
