### ISSUE TITLE
今天拿了新的下来发现图片文件里面可能有点问题

### ISSUE THREAD

**Issue by lovebluedan** [JsonChao/Awesome-WanAndroid#7]
Error:Some file crunching failed, see logs for details
Error:Execution failed for task ':app:mergeDebugResources'.
> Error: Some file crunching failed, see logs for details
我在编译的时候报这个错，可能是图片有哪里出了问题，应该是近期提交的.9图什么的
希望你可以核对一下 谢谢~

**Comment by JsonChao** [comment]
我这边能正常编译，看看这个https://blog.csdn.net/u013132758/article/details/70187175  能否帮助你，第一个解决方案试试
