### ISSUE TITLE
点击搜索栏闪退问题

### ISSUE THREAD

**Issue by LLhon** [JsonChao/Awesome-WanAndroid#72]
机型：华为荣耀 LLD AL20
系统：8.0

偶发性闪退，看issues说先卸载再重装，但我想知道为啥会出现这种闪退问题，还有如何从根本上解决这个问题呢

崩溃日志：
`java.lang.RuntimeException:Unable to start activity ComponentInfo{com.xxx/com.xxx.mvp.ui.home.activity.SearchActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.xxx.core.dao.SearchHistoryDataDao com.xxx.core.dao.DaoSession.getSearchHistoryDataDao()' on a null object reference
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3194)
 ......
java.lang.NullPointerException:Attempt to invoke virtual method 'com.xxx.core.dao.SearchHistoryDataDao com.xxx.core.dao.DaoSession.getSearchHistoryDataDao()' on a null object reference
com.xxx.core.db.DbHelperImpl.java.util.List loadAllSearchHistoryData()(Unknown Source:2)
`

**Comment by JsonChao** [comment]
Thank your issue，看你的日志，这个可能是数据库没有创建DaoSeesion所致，可能是华为机型的兼容性问题，后续有时间会寻找此型号的手机来验证解决问题~

**Comment by JsonChao** [comment]
找到问题了，在Application中，有如下代码
![image](https://user-images.githubusercontent.com/17464480/47988426-240e0580-e11d-11e8-9445-abe0601b5eeb.png)，
可以看到DaggerAppComponent的初始化在数据库的DaoSeesion初始化之前，因此，
![image](https://user-images.githubusercontent.com/17464480/47988488-4dc72c80-e11d-11e8-82d7-dc0e82060058.png)
可知此时得到的DaoSeesion可能为空，将代码改成如下即可。
![image](https://user-images.githubusercontent.com/17464480/47988583-90890480-e11d-11e8-83f9-7d34364a4eab.png)

**Comment by LLhon** [comment]
很强👍，多谢啦
