### ISSUE TITLE
大神，项目写的挺好的，切换夜间模式是怎么实现的呢？我看了代码不明所以，请赐教

### ISSUE THREAD

**Issue by gaoleicoding** [JsonChao/Awesome-WanAndroid#76]
@Override
    

public void useNightMode(boolean isNight) {
        if (isNight) {
            AppCompatDelegate.setDefaultNightMode(
                    AppCompatDelegate.MODE_NIGHT_YES);
        } else {
            AppCompatDelegate.setDefaultNightMode(
                    AppCompatDelegate.MODE_NIGHT_NO);
        }
        recreate();
    }

我看您的主题也没应用Theme.AppCompat.DayNight呢

**Comment by JsonChao** [comment]
Thank your issue，这个夜间模式切换是在资源文件夹里配置了2套对应的颜色，同一个id对应颜色在白天模式是白色，在晚上是黑色，就这么简单~
