### ISSUE TITLE
HTTPS 证书认证在哪呀？

### ISSUE THREAD

**Issue by stewForAni** [JsonChao/Awesome-WanAndroid#88]
你好，你的  HTTPS 证书认证在哪呀？
我貌似没有找到 这个步骤。

我发现你的https接口证书都是CA机构颁发的，所以你没有https认证这一步么？

我现在报了一个问题：javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

**Comment by JsonChao** [comment]
Thank your issue，是的，由于刚刚更新到https配置，还没来得及配置证书认证这块，对于没有经过CA认证的自签名证书的网站是会出现这个问题的，后续会尽快加上的~
