### ISSUE TITLE
没有看明白这个网络请求是怎么回事

### ISSUE THREAD

**Issue by SmallYQ** [JsonChao/Awesome-WanAndroid#89]
![image](https://user-images.githubusercontent.com/31333216/54831502-65cad180-4cf5-11e9-89da-745046a2b5e4.png)
![image](https://user-images.githubusercontent.com/31333216/54831536-78450b00-4cf5-11e9-8cac-4e26b7ce501b.png)
![image](https://user-images.githubusercontent.com/31333216/54831592-96127000-4cf5-11e9-909d-bb6e55ad14d5.png)
![image](https://user-images.githubusercontent.com/31333216/54831620-a32f5f00-4cf5-11e9-81f2-8efcfc23fb50.png)
这里没有看明白是怎么进行网络请求的，不是说用retrofit网络框架的吗？？？大佬求解释

**Comment by JsonChao** [comment]
Thank your issue，这里是用的Retrofit，在HttpHelperImpl的构造方法中使用@Inject构造器的方式将GeekApi注入进来了，具体是由HttpModule的provideGeeksApi方法提供的，如下所示：

@Module
public class HttpModule {

    @Singleton
    @Provides
    GeeksApis provideGeeksApi(@WanAndroidUrl Retrofit retrofit) {
        return retrofit.create(GeeksApis.class);
    }
    ...
 }
