### ISSUE TITLE
有个小问题，下滑之后，顶部的状态栏的文字，和界面重合。这样是否不太好？

### ISSUE THREAD

**Issue by HuaZaiWuDi** [JsonChao/Awesome-WanAndroid#9]
![qq 20180416095000](https://user-images.githubusercontent.com/26106636/38786591-8d8d8e0c-415b-11e8-9249-c4f0b9864152.png)

**Comment by JsonChao** [comment]
Thanks your issue，已将此问题列入下个版本计划~
