### ISSUE TITLE
滑动时右下角小火箭也滑下去了 那不是相当于没用了嘛

### ISSUE THREAD

**Issue by TwilightKHQ** [JsonChao/Awesome-WanAndroid#90]
![Screenshot_1553678303](https://user-images.githubusercontent.com/25874642/55064159-780d8c80-50b4-11e9-893e-0db97e2feb12.png)
![Screenshot_1553678353](https://user-images.githubusercontent.com/25874642/55064201-88256c00-50b4-11e9-9a74-1e020d6267a8.png)

**Comment by stewForAni** [comment]
相信贵公司的app体验应该不咋地 ╮(╯▽╰)╭

**Comment by JsonChao** [comment]
Thank your issue，这个设计我是这样考虑的：当用户上滑查看列表下面的内容时，应该将小火箭隐藏，因为用户此时不需要小火箭的滚动到顶部的功能，当用户下滑一下想看到顶部的内容时，应该将小火箭弹出，因为用户此时需要小火箭的滚动到顶部的功能。

**Comment by TwilightKHQ** [comment]
只是以一个用户的角度来讲，回到顶部的操作需要先下滑再点击的两步操作的体验，远不如一个点击操作即可回到顶部的好。
