### ISSUE TITLE
retrofit的问题

### ISSUE THREAD

**Issue by ilatent** [JsonChao/Awesome-WanAndroid#95]
大神，想知道你的retrofit在那里初始化了，你的请求又是在哪里放到了retorift中发起请求的，为什么我看你都是直接调用httpHelper中的请求，并没有放入到retofit去啊，我翻遍了你的程序也没能找到它。

**Comment by JsonChao** [comment]
Thank your issue，网络模块配置是间接通过dagger进行注入和依赖管理的，参见HttpModule～

**Comment by gdchent** [comment]
感觉dagger不好下手
