### ISSUE TITLE
labrary sources does not match the bytecode for class SupportActivity

### ISSUE THREAD

**Issue by jdhdevelop** [JsonChao/Awesome-WanAndroid#99]
你好，我在我的demo里面复制你的整个架构想学习一下，没有直接fork。然后fragmentation的这个依赖是完全和你一样的。但是我的工程报这个错。然后我发现AS会加载.gradle\caches\transform-1或者transform-2这两文件下的东西，和modules-2里面的不一样。而且我还没有fragmentation-core这个aar。但是你的工程里有。我就搞不懂是怎么回事。菜鸟请大佬指点。

**Comment by JsonChao** [comment]
Thank your issue，建议依赖全都copy过来，clean再build加同步~
